### PR TITLE
Embbed 'how to install openstack' video in homepage

### PR DESCRIPTION
**Pull request by petesfrench**
## Done

- Embbed 'how to install openstack' video in homepage based on [copydoc](https://docs.google.com/document/d/1-QO5zAclj469qGvFmNJBjQ_qqI_T_uliwj6mAo8ZbCs/edit)

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: http://0.0.0.0:8039/
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- [List additional steps to QA the new features or prove the bug has been resolved]

## Issue / Card

Fixes https://warthogs.atlassian.net/browse/WD-6019

### CODE REVIEW

**Comment by petesfrench** [comment]
@mtruj013 sure thing, what is the issue with the suru?

**Comment by mtruj013** [comment]
@petesfrench it's supposed to be black, not orange, like so https://web.archive.org/web/20230804084639/https://microstack.run/

Or at least that was the case when revamped this a couple months ago for the sunbeam launch. Tagging @julpal7 to confirm just in case

**Comment by petesfrench** [comment]
Not sure when it got reverted, but it has been orange on live for a long time now.

Anyway, I have updated it back to the black theme, do you want to take one last look @mtruj013 ?

**Comment by mtruj013** [comment]
> Not sure when it got reverted, but it has been orange on live for a long time now.

I think it's cause of how surus are built in Vanilla 4. At least that's my guess since the same thing happened on microk8s when we bumped the version

Anyways, LGTM!

**Comment by petesfrench** [comment]
@mtruj013 That makes sense, thanks for the info. Will keep an eye out for  it on other sites.

**Pull request merged**
